server:
  servlet:
    context-path: /funcionarios/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/funcionarios 
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update 

springdoc:
  swagger-ui:
    path: /public/swagger
